[build]
  command = "bash install-rust.sh && cd frontend && npm install && npm run build"

[build.environment]
  RUSTUP_HOME = "/opt/buildhome/.rustup"
  CARGO_HOME = "/opt/buildhome/.cargo"
  PYTHON_VERSION = "3.11"
